criaCartao('TEMA: História', 'PERGUNTA: Quem descobriu o Brasil?', 'RESPOSTA: Pedro Álvares Cabral.');
criaCartao('TEMA: Geografia', 'PERGUNTA: Qual é o rio mais extenso do mundo?', 'RESPOSTA: Rio Amazonas.');
criaCartao('TEMA: Ciências', 'PERGUNTA: Qual elemento químico tem o símbolo O?', 'RESPOSTA: Oxigênio.');
criaCartao('TEMA: Literatura', 'PERGUNTA: Quem escreveu "O Pequeno Príncipe"?', 'RESPOSTA: Antoine de Saint-Exupéry.');
criaCartao('TEMA: Música', 'PERGUNTA: Qual banda lançou o álbum "Abbey Road"?', 'RESPOSTA: The Beatles.');
criaCartao('TEMA: Cinema', 'PERGUNTA: Qual foi o primeiro filme da Marvel no MCU?', 'RESPOSTA: Homem de Ferro (2008).');
criaCartao('TEMA: Matemática', 'PERGUNTA: O que é um número primo?', 'RESPOSTA: Um número que só pode ser dividido por 1 e por ele mesmo.');
criaCartao('TEMA: Astronomia', 'PERGUNTA: Qual planeta tem um sistema de anéis visíveis?', 'RESPOSTA: Saturno.');
criaCartao('TEMA: Tecnologia', 'PERGUNTA: Quem fundou a Microsoft?', 'RESPOSTA: Bill Gates e Paul Allen.');
criaCartao('TEMA: Esportes', 'PERGUNTA: Quantas jogadoras compõem um time de voleibol em quadra?', 'RESPOSTA: Seis.');
criaCartao('TEMA: Biologia', 'PERGUNTA: Qual é a molécula responsável pela hereditariedade?', 'RESPOSTA: DNA.');
criaCartao('TEMA: Economia', 'PERGUNTA: Qual é a moeda oficial do Reino Unido?', 'RESPOSTA: Libra Esterlina.');
criaCartao('TEMA: Física', 'PERGUNTA: Qual é a unidade de medida da força?', 'RESPOSTA: Newton.');
criaCartao('TEMA: Mitologia', 'PERGUNTA: Quem era o deus do sol na mitologia egípcia?', 'RESPOSTA: Rá.');
criaCartao('TEMA: Política', 'PERGUNTA: Quantos estados tem o Brasil?', 'RESPOSTA: 26 estados e o Distrito Federal.');
criaCartao('TEMA: História', 'PERGUNTA: Em que ano ocorreu a Revolução Francesa?', 'RESPOSTA: 1789.');
criaCartao('TEMA: Geografia', 'PERGUNTA: Qual é a capital da Austrália?', 'RESPOSTA: Canberra.');
criaCartao('TEMA: Ciências', 'PERGUNTA: O que é a camada de ozônio?', 'RESPOSTA: Uma camada da atmosfera que protege a Terra dos raios UV.');
criaCartao('TEMA: Literatura', 'PERGUNTA: Quem escreveu "Dom Casmurro"?', 'RESPOSTA: Machado de Assis.');
criaCartao('TEMA: Música', 'PERGUNTA: Quem compôs a ópera "A Flauta Mágica"?', 'RESPOSTA: Wolfgang Amadeus Mozart.');
criaCartao('TEMA: Cinema', 'PERGUNTA: Quem dirigiu o filme "Titanic"?', 'RESPOSTA: James Cameron.');
criaCartao('TEMA: Matemática', 'PERGUNTA: Qual é a fórmula para calcular a área de um triângulo?', 'RESPOSTA: Base x Altura ÷ 2.');
criaCartao('TEMA: Astronomia', 'PERGUNTA: Qual é a estrela mais próxima da Terra?', 'RESPOSTA: O Sol.');
criaCartao('TEMA: Tecnologia', 'PERGUNTA: O que significa a sigla "Wi-Fi"?', 'RESPOSTA: Wireless Fidelity.');
criaCartao('TEMA: Esportes', 'PERGUNTA: Em que ano foram realizados os primeiros Jogos Olímpicos modernos?', 'RESPOSTA: 1896.');
criaCartao('TEMA: Biologia', 'PERGUNTA: Qual é o nome científico da espécie humana?', 'RESPOSTA: Homo sapiens.');
criaCartao('TEMA: Economia', 'PERGUNTA: O que é inflação?', 'RESPOSTA: O aumento generalizado dos preços em uma economia.');
criaCartao('TEMA: Física', 'PERGUNTA: Qual é a velocidade da luz no vácuo?', 'RESPOSTA: Aproximadamente 300.000 km/s.');
criaCartao('TEMA: Mitologia', 'PERGUNTA: Quem era o deus grego dos mares?', 'RESPOSTA: Poseidon.');
criaCartao('TEMA: Política', 'PERGUNTA: Qual é a função principal do Poder Legislativo?', 'RESPOSTA: Criar e aprovar leis.');
criaCartao('TEMA: História', 'PERGUNTA: Quem foi o primeiro imperador do Brasil?', 'RESPOSTA: Dom Pedro I.');
criaCartao('TEMA: Geografia', 'PERGUNTA: Qual é o maior país do mundo em área?', 'RESPOSTA: Rússia.');
criaCartao('TEMA: Ciências', 'PERGUNTA: O que é fotossíntese?', 'RESPOSTA: O processo pelo qual as plantas produzem energia utilizando luz solar.');
criaCartao('TEMA: Literatura', 'PERGUNTA: Quem escreveu "A Odisséia"?', 'RESPOSTA: Homero.');
criaCartao('TEMA: Música', 'PERGUNTA: Qual cantor é conhecido como "Rei do Pop"?', 'RESPOSTA: Michael Jackson.');
criaCartao('TEMA: Cinema', 'PERGUNTA: Qual filme ganhou o Oscar de Melhor Filme em 2023?', 'RESPOSTA: Tudo em Todo Lugar ao Mesmo Tempo.');
criaCartao('TEMA: Matemática', 'PERGUNTA: Quanto é 9 x 9?', 'RESPOSTA: 81.');
criaCartao('TEMA: Astronomia', 'PERGUNTA: O que é uma galáxia?', 'RESPOSTA: Um grande sistema de estrelas, gás e poeira ligados pela gravidade.');
criaCartao('TEMA: Tecnologia', 'PERGUNTA: Qual foi o primeiro computador pessoal?', 'RESPOSTA: Altair 8800.');
criaCartao('TEMA: Esportes', 'PERGUNTA: Quem é o maior artilheiro da história da Copa do Mundo?', 'RESPOSTA: Miroslav Klose.');
criaCartao('TEMA: Biologia', 'PERGUNTA: O que são células-tronco?', 'RESPOSTA: Células capazes de se transformar em outros tipos de células.');
criaCartao('TEMA: Economia', 'PERGUNTA: Qual é a função do Banco Central?', 'RESPOSTA: Regular a moeda e o sistema financeiro de um país.');
criaCartao('TEMA: Física', 'PERGUNTA: Quem desenvolveu a teoria da relatividade?', 'RESPOSTA: Albert Einstein.');
criaCartao('TEMA: Mitologia', 'PERGUNTA: Quem era a deusa da sabedoria na mitologia grega?', 'RESPOSTA: Atena.');
criaCartao('TEMA: Política', 'PERGUNTA: O que é democracia?', 'RESPOSTA: Um sistema de governo em que o poder é exercido pelo povo.');
criaCartao('TEMA: História', 'PERGUNTA: Em que ano caiu o Muro de Berlim?', 'RESPOSTA: 1989.');
criaCartao('TEMA: Geografia', 'PERGUNTA: Qual é o menor país do mundo?', 'RESPOSTA: Vaticano.');
criaCartao('TEMA: Ciências', 'PERGUNTA: Qual é a principal função dos glóbulos vermelhos?', 'RESPOSTA: Transportar oxigênio pelo corpo.');
criaCartao('TEMA: Literatura', 'PERGUNTA: Quem escreveu "Cem Anos de Solidão"?', 'RESPOSTA: Gabriel García Márquez.');
criaCartao('TEMA: Esportes', 'PERGUNTA: Qual é o esporte mais praticado no mundo?', 'RESPOSTA: Futebol.');



